"""include_status_property_to_submissions_entity

Revision ID: 3bf4feb26071
Revises: 838e29cf62f4
Create Date: 2026-09-05 15:32:53.149996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3bf4feb26071"
down_revision: Union[str, Sequence[str], None] = "838e29cf62f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE submission_status AS ENUM ('SUCCESS', 'FAILED')")
    
    op.add_column(
        "submissions",
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS", "FAILED", name="submission_status", create_constraint=False
            ),
            nullable=False,
            server_default="FAILED",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "status")
    
    op.execute("DROP TYPE submission_status")
    # ### end Alembic commands ###
