"""include_origin_property_to_submissions_entity

Revision ID: 4d84ba2c8541
Revises: 3bf4feb26071
Create Date: 2026-09-05 17:52:48.598279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d84ba2c8541"
down_revision: Union[str, Sequence[str], None] = "3bf4feb26071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submissions",
        sa.Column("origin", sa.Text(), nullable=False, server_default="*"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "origin")
    # ### end Alembic commands ###
