"""update_widget_include_domain_whitelist

Revision ID: 838e29cf62f4
Revises: 85ac6dd37454
Create Date: 2026-09-04 16:36:22.028330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838e29cf62f4'
down_revision: Union[str, Sequence[str], None] = '85ac6dd37454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('domain_whitelist', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('widgets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('widgets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'deleted_at')
    op.drop_column('widgets', 'is_deleted')
    op.drop_column('widgets', 'domain_whitelist')
    # ### end Alembic commands ###
